{
 "title": "MassTransit - Messages Monitoring",
 "description": "MassTransit is a message-based distributed application framework for .NET http://masstransit-project.com.\r\n\r\nMassTransit supports Prometheus metric capture, which provides useful observability into the bus, endpoints, consumers, and messages.\r\n\r\nThis dashboard shows the messages published and sent using MassTransit framework.",
 "tags": [
  "MassTransit",
  "Event Driven Architecture"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "environment", "label": "Environment", "query": { "query": "label_values(env)" } },
   { "name": "domain", "label": "Domain", "query": { "query": "label_values(domain)" } },
   { "name": "application", "label": "Application", "query": { "query": "label_values(app)" } },
   { "name": "MessageType", "label": "Message Type", "query": { "query": "label_values(message_type)" } },
   { "name": "ConsumerType", "label": "Consumer Type", "query": { "query": "label_values(consumer_type)" } },
   {
    "name": "PublishMessageType",
    "label": "Publish Message Type",
    "query": {
     "query": "label_values(mt_publish_total,message_type)"
    }
   },
   {
    "name": "SendMessageType",
    "label": "Send Message Type",
    "query": {
     "query": "label_values(mt_send_total,message_type)"
    }
   },
   {
    "name": "SagaType",
    "query": {
     "query": "label_values(mt_saga_in_progress,consumer_type)"
    }
   },
   {
    "name": "SagaMessageType",
    "query": {
     "query": "label_values(mt_saga_in_progress,message_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages Published (Events)",
   "type": "table",
   "description": "Events are objects published and broadcasted to be picked up by all consumers that are listening to that event type. It means that something has happened. (e.g.: UserUpdated)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(mt_publish_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__range])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Messages Sent (Commands)",
   "type": "table",
   "description": "Commands are objects sent direct to an endpoint and will be picked up by the first consumer that implements it. It means that something must be performed after receiving that message.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(mt_send_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bus instances",
   "type": "stat",
   "description": "Number of bus instances",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(mt_bus{env=\"$environment\",app=~\"$application\"})"
    }
   ]
  },
  {
   "title": "Messages Consumed",
   "type": "table",
   "description": "Total number of messages consumed",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "increase(mt_consume_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\",consumer_type=~\"$ConsumerType\"}[$__range])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Producers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Publish Total",
   "type": "stat",
   "description": "Total number of messages consumed (one to many events)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(mt_publish_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Publish Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(mt_publish_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Publish Fault Total",
   "type": "stat",
   "description": "Total number of message publish faults",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(mt_publish_fault_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Publish Fault Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(mt_publish_fault_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Send Total",
   "type": "stat",
   "description": "Total number of messages sent (one to one commands)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(mt_send_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Send Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(mt_send_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Send Fault Total",
   "type": "stat",
   "description": "Total number of message send faults",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(mt_send_fault_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Send Fault Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(mt_send_fault_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Consume Total",
   "type": "stat",
   "description": "Total number of messages consumed",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(mt_consume_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Consume Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(mt_consume_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Consume Fault Total",
   "type": "stat",
   "description": "Total number of message consume faults",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mt_consume_fault_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Consume Fault Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(mt_consume_fault_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Consume endpoints total",
   "type": "stat",
   "description": "Number of receive endpoint instances.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(mt_endpoint{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"})"
    }
   ]
  },
  {
   "title": "Consumers in progress",
   "type": "stat",
   "description": "Number of consumers in progress",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(mt_consumer_in_progress{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Consume Retry Total",
   "type": "stat",
   "description": "Total number of message consume retries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(mt_consume_retry_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Consume Retry Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(mt_consume_retry_total{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Consume Duration (Seconds)",
   "type": "timeseries",
   "description": "Elapsed time spent consuming a message, in seconds.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mt_consume_duration_seconds_bucket{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__rate_interval])) by (message_type,le))  ",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Delivery Duration (Seconds)",
   "type": "timeseries",
   "description": "Elapsed time between when the message was sent and when it was consumed, in seconds.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mt_delivery_duration_seconds_bucket{env=\"$environment\",app=~\"$application\",message_type=~\"$MessageType\"}[$__rate_interval])) by (message_type,le))",
     "legendFormat": "{{message_type}}"
    }
   ]
  }
 ]
}